name: country_code_picker_minimal
description: A flutter package to display a country code selector. It also gives the possibility to select a list of favorite countries, as well as perform searches using a simple, fully customizable search box. based on CountryCodePicker.
version: 0.0.1
homepage: https://github.com/chandrabezzo/CountryCodePicker
repository: https://github.com/chandrabezzo/CountryCodePicker
issue_tracker: https://github.com/imtoori/CountryCodePicker/issues

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  assets:
    - flags/
    - packages/country_code_picker_minimal/src/i18n/af.json
    - packages/country_code_picker_minimal/src/i18n/am.json
    - packages/country_code_picker_minimal/src/i18n/ha.json
    - packages/country_code_picker_minimal/src/i18n/ku.json
    - packages/country_code_picker_minimal/src/i18n/ml.json
    - packages/country_code_picker_minimal/src/i18n/no.json
    - packages/country_code_picker_minimal/src/i18n/ps.json
    - packages/country_code_picker_minimal/src/i18n/sd.json
    - packages/country_code_picker_minimal/src/i18n/so.json
    - packages/country_code_picker_minimal/src/i18n/sq.json
    - packages/country_code_picker_minimal/src/i18n/ta.json
    - packages/country_code_picker_minimal/src/i18n/tg.json
    - packages/country_code_picker_minimal/src/i18n/tt.json
    - packages/country_code_picker_minimal/src/i18n/ug.json
    - packages/country_code_picker_minimal/src/i18n/ur.json
    - packages/country_code_picker_minimal/src/i18n/vi.json
    - packages/country_code_picker_minimal/src/i18n/ar.json
    - packages/country_code_picker_minimal/src/i18n/az.json
    - packages/country_code_picker_minimal/src/i18n/be.json
    - packages/country_code_picker_minimal/src/i18n/bg.json
    - packages/country_code_picker_minimal/src/i18n/bn.json
    - packages/country_code_picker_minimal/src/i18n/bs.json
    - packages/country_code_picker_minimal/src/i18n/ca.json
    - packages/country_code_picker_minimal/src/i18n/cs.json
    - packages/country_code_picker_minimal/src/i18n/da.json
    - packages/country_code_picker_minimal/src/i18n/de.json
    - packages/country_code_picker_minimal/src/i18n/el.json
    - packages/country_code_picker_minimal/src/i18n/en.json
    - packages/country_code_picker_minimal/src/i18n/es.json
    - packages/country_code_picker_minimal/src/i18n/et.json
    - packages/country_code_picker_minimal/src/i18n/fa.json
    - packages/country_code_picker_minimal/src/i18n/fi.json
    - packages/country_code_picker_minimal/src/i18n/fr.json
    - packages/country_code_picker_minimal/src/i18n/gl.json
    - packages/country_code_picker_minimal/src/i18n/el.json
    - packages/country_code_picker_minimal/src/i18n/he.json
    - packages/country_code_picker_minimal/src/i18n/hi.json
    - packages/country_code_picker_minimal/src/i18n/hr.json
    - packages/country_code_picker_minimal/src/i18n/hu.json
    - packages/country_code_picker_minimal/src/i18n/hy.json
    - packages/country_code_picker_minimal/src/i18n/id.json
    - packages/country_code_picker_minimal/src/i18n/is.json
    - packages/country_code_picker_minimal/src/i18n/it.json
    - packages/country_code_picker_minimal/src/i18n/ja.json
    - packages/country_code_picker_minimal/src/i18n/ka.json
    - packages/country_code_picker_minimal/src/i18n/kk.json
    - packages/country_code_picker_minimal/src/i18n/km.json
    - packages/country_code_picker_minimal/src/i18n/ko.json
    - packages/country_code_picker_minimal/src/i18n/ky.json
    - packages/country_code_picker_minimal/src/i18n/lt.json
    - packages/country_code_picker_minimal/src/i18n/lv.json
    - packages/country_code_picker_minimal/src/i18n/mk.json
    - packages/country_code_picker_minimal/src/i18n/mn.json
    - packages/country_code_picker_minimal/src/i18n/ms.json
    - packages/country_code_picker_minimal/src/i18n/nb.json
    - packages/country_code_picker_minimal/src/i18n/nl.json
    - packages/country_code_picker_minimal/src/i18n/nn.json
    - packages/country_code_picker_minimal/src/i18n/pl.json
    - packages/country_code_picker_minimal/src/i18n/pt.json
    - packages/country_code_picker_minimal/src/i18n/ro.json
    - packages/country_code_picker_minimal/src/i18n/ru.json
    - packages/country_code_picker_minimal/src/i18n/sk.json
    - packages/country_code_picker_minimal/src/i18n/sl.json
    - packages/country_code_picker_minimal/src/i18n/sr.json
    - packages/country_code_picker_minimal/src/i18n/sv.json
    - packages/country_code_picker_minimal/src/i18n/th.json
    - packages/country_code_picker_minimal/src/i18n/tr.json
    - packages/country_code_picker_minimal/src/i18n/uk.json
    - packages/country_code_picker_minimal/src/i18n/uz.json
    - packages/country_code_picker_minimal/src/i18n/zh.json


